washingtonstateuniversity/WSUWP-Admin

wsuwp-admin.php

In our initial support of Duplicate and Merge Posts, we won't be using the submit for review workflow.

[PR] Add filters in prep for Duplicate and Merge Posts

---

wsuwp-admin.php

[PR] Use the gmt_offset option to display a more accurate last updated

---

wsuwp-admin.php

Catch any checks for theme updates and remove some custom themes
from the object that may conflict with existing slugs in the
WordPress theme repository.

[PR] Exclude select custom themes from theme update check

---

wsuwp-admin.php

Specifically, this allows us to use BuddyPress on a single site
for testing before releasing it into the wild. :)
Ideally this is handled much nicer in the future.

[PR] Manually remove some plugins from some plugin views

---

wsuwp-admin.php

Not exactly sure what the long term implications of this are, so being cautious for now.

[PR] Restrict WSUWP JSON Web Templates to Admissions site for now

---

wsuwp-admin.php

[PR] Account for password protected documents when setting content type headers

---

CHANGELOG.md
wsuwp-admin.php

This used to live in the WSUWP Platform project, but makes more sense as a WSU specific decision.

[PR] Register default taxonomies for pages and media

---

wsuwp-admin.php

We don't need the large list of supported embeds, but we can still take advantage of many for now, more when we're ready.

[PR] Adjust default behavior provided by Shortcake Bakery

---

wsuwp-admin.php

[PR] Use `$request` as the local var rather than `$this`

---

wsuwp-admin.php

We should keep this functionality together.

[PR] Transfer removal of Events Calendar action to Extended Events plugin

---

wsuwp-admin.php

We only want to provide support for this at people.wsu.edu, not on all platform sites.

[PR] Restrict the WSU People Directory from appearing as a plugin

---

wsuwp-admin.php

This filter is applied in the WSUWP SSO Authentication plugin.
This should be merged with https://github.com/washingtonstateuniversity/WSUWP-Plugin-SSO-Authentication/pull/51

[PR] Create new network user when a valid NID authenticates

---

wsuwp-admin.php

This completes support for WP Document Revisions. See https://github.com/washingtonstateuniversity/WSUWP-Content-Visibility/pull/16

[PR] Filter content visibility capabilities to include read_document

---

wsuwp-admin.php

@jeremyfelt Merging due to time, but #reviewlater.

[PR] Restrict the Make Plus plugin to the ASWSU site

---

wsuwp-admin.php

Research wants to allow specific users to submit events and this add-on will let them do that.
@jeremyfelt #reviewmerge?
#felt4life #hashtag

[PR] Added Research Site for Community Events add-on

---

wsuwp-admin.php

This made it hard to use some of the restricted plugins in a dev
environment.

[PR] Use the site domain when restricting plugins on dev

---

CHANGELOG.md
includes/class-wsuwp-admin.php
package.json
wsuwp-admin.php

[PR] Fix filepath

---

includes/class-wsuwp-admin.php

These have been moved to a new plugin. See https://github.com/washingtonstateuniversity/WSUWP-Extended-Shortcode-UI/pull/2

[PR] Remove Shortcake Bakery extensions

---

includes/class-wsuwp-admin.php

This prevents the UI from appearing on all public post types.

[PR] Limit Editorial Access Manager to specific post types

---

CHANGELOG.md
includes/wsuwp-admin-remarketing.php
wsuwp-admin.php

This keeps the existing WSUWP Admin plugin structure, but starts the conversion to the new skeleton version by introducing a namespaced file. :)

[PR] Add a way to manage multiple remarketing pixels. Add etm.wsu.edu pixel.

---

includes/wsuwp-admin-remarketing.php

This ensures it is output last and after the conversion ID

[PR] Output the Google conversion script directory

---

includes/class-wsuwp-admin.php
includes/common.php
includes/response-headers.php
wsuwp-admin.php

This was previously called as a method in the class and now causes a fatal error. :(

[PR] Move `post_password_required()` to a common location

---

CHANGELOG.md
includes/s3-uploads.php
package-lock.json
package.json
wsuwp-admin.php

Fix bug in s3.wp.wsu.edu cache invalidation

---

includes/content-visibility.php
wsuwp-admin.php

This adds the group as avaiable to use in WSU Content Visibility for the AOI support staging site. We'll need to update the check on the site domain and path when the site goes live.

[PR] Add AOI.Employees.All as an available Content Visibility group

---

CHANGELOG.md
includes/content-visibility.php
package-lock.json
package.json
wsuwp-admin.php

Fixes a fatal error in production. 🎉

[PR] Use root namespace for WP_User in Content Visibility

---

CHANGELOG.md
includes/akismet.php
includes/class-wsuwp-admin.php
includes/msm-sitemap.php
package-lock.json
package.json
wsuwp-admin.php

Also moves previous MSM Sitemaps filter to new file.

[PR] Add support for pages to MSM Sitemaps

---

CHANGELOG.md
includes/class-wsuwp-admin.php
package-lock.json
package.json
wsuwp-admin.php

The plugin is already activated, but it would be nice if it displayed in the list :)

Make WP Event Calendar visible on events.wsu.edu

---

CHANGELOG.md
includes/class-wsuwp-admin.php
package-lock.json
package.json
wsuwp-admin.php

Whitelisted broadband.wsu.edu to:
- CAHNRS WSUWP Pagebuilder 3.0
- CAHNRS WSUWP Plugin Core
- CAHNRS WSUWP Plugin Extension Core
Updated framenetworks.cw.wsu.edu to framenetworks.wsu.edu

[PR] Cahnrs sites plugins

---

includes/class-wsuwp-admin.php
wsuwp-admin.php

- White listed https://business.wsu.edu/celebratecarson for the SEO plugin.

[PR] Add SEO to Business
